"""add cita_id to predicciones

Revision ID: 44d66f6f0f1f
Revises: 20260614_0001
Create Date: 2026-06-14 00:06:30.136322
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '44d66f6f0f1f'
down_revision = '20260614_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('citas', 'estado',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=40),
               nullable=False,
               existing_server_default=sa.text("'pendiente'::character varying"))
    op.alter_column('citas', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_citas_fecha'), table_name='citas')
    op.drop_index(op.f('idx_citas_medico'), table_name='citas')
    op.drop_index(op.f('idx_citas_paciente'), table_name='citas')
    op.create_index(op.f('ix_citas_fecha_cita'), 'citas', ['fecha_cita'], unique=False)
    op.create_index(op.f('ix_citas_id'), 'citas', ['id'], unique=False)
    op.create_index(op.f('ix_citas_medico_id'), 'citas', ['medico_id'], unique=False)
    op.create_index(op.f('ix_citas_paciente_id'), 'citas', ['paciente_id'], unique=False)
    op.drop_constraint(op.f('citas_paciente_id_fkey'), 'citas', type_='foreignkey')
    op.create_foreign_key(None, 'citas', 'pacientes', ['paciente_id'], ['id'])
    op.alter_column('datos_clinicos', 'fecha_registro',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_dc_paciente'), table_name='datos_clinicos')
    op.create_index(op.f('ix_datos_clinicos_id'), 'datos_clinicos', ['id'], unique=False)
    op.create_index(op.f('ix_datos_clinicos_medico_id'), 'datos_clinicos', ['medico_id'], unique=False)
    op.create_index(op.f('ix_datos_clinicos_paciente_id'), 'datos_clinicos', ['paciente_id'], unique=False)
    op.drop_constraint(op.f('datos_clinicos_paciente_id_fkey'), 'datos_clinicos', type_='foreignkey')
    op.create_foreign_key(None, 'datos_clinicos', 'pacientes', ['paciente_id'], ['id'])
    op.alter_column('disponibilidad_medica', 'disponible',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_disponibilidad_medica_id'), 'disponibilidad_medica', ['id'], unique=False)
    op.create_index(op.f('ix_disponibilidad_medica_medico_id'), 'disponibilidad_medica', ['medico_id'], unique=False)
    op.drop_constraint(op.f('disponibilidad_medica_medico_id_fkey'), 'disponibilidad_medica', type_='foreignkey')
    op.create_foreign_key(None, 'disponibilidad_medica', 'medicos', ['medico_id'], ['id'])
    op.alter_column('email_logs', 'fecha_evento',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_email_logs_id'), 'email_logs', ['id'], unique=False)
    op.create_index(op.f('ix_email_logs_recomendacion_id'), 'email_logs', ['recomendacion_id'], unique=False)
    op.alter_column('medicos', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_medicos_id'), 'medicos', ['id'], unique=False)
    op.drop_constraint(op.f('medicos_usuario_id_fkey'), 'medicos', type_='foreignkey')
    op.create_foreign_key(None, 'medicos', 'usuarios', ['usuario_id'], ['id'])
    op.alter_column('pacientes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('pacientes_dni_key'), 'pacientes', type_='unique')
    op.create_index(op.f('ix_pacientes_dni'), 'pacientes', ['dni'], unique=True)
    op.create_index(op.f('ix_pacientes_id'), 'pacientes', ['id'], unique=False)
    op.drop_constraint(op.f('permisos_codigo_key'), 'permisos', type_='unique')
    op.create_index(op.f('ix_permisos_codigo'), 'permisos', ['codigo'], unique=True)
    op.create_index(op.f('ix_permisos_id'), 'permisos', ['id'], unique=False)
    op.add_column('predicciones', sa.Column('cita_id', sa.Integer(), nullable=True))
    op.alter_column('predicciones', 'fecha_prediccion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_pred_fecha'), table_name='predicciones')
    op.drop_index(op.f('idx_pred_medico'), table_name='predicciones')
    op.drop_index(op.f('idx_pred_paciente'), table_name='predicciones')
    op.create_index(op.f('ix_predicciones_cita_id'), 'predicciones', ['cita_id'], unique=False)
    op.create_index(op.f('ix_predicciones_datos_clinicos_id'), 'predicciones', ['datos_clinicos_id'], unique=False)
    op.create_index(op.f('ix_predicciones_id'), 'predicciones', ['id'], unique=False)
    op.create_index(op.f('ix_predicciones_medico_id'), 'predicciones', ['medico_id'], unique=False)
    op.create_index(op.f('ix_predicciones_paciente_id'), 'predicciones', ['paciente_id'], unique=False)
    op.drop_constraint(op.f('predicciones_paciente_id_fkey'), 'predicciones', type_='foreignkey')
    op.create_foreign_key(None, 'predicciones', 'pacientes', ['paciente_id'], ['id'])
    op.create_foreign_key(None, 'predicciones', 'citas', ['cita_id'], ['id'], ondelete='SET NULL')
    op.drop_table_comment(
        'predicciones',
        existing_comment='Resultados generados por modelos LR/RF luego del preprocesamiento de radiografias 64x64 en escala de grises.',
        schema=None
    )
    op.alter_column('recomendaciones', 'email_enviado',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('recomendaciones', 'fecha_generacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_rec_medico'), table_name='recomendaciones')
    op.drop_index(op.f('idx_rec_paciente'), table_name='recomendaciones')
    op.create_index(op.f('ix_recomendaciones_id'), 'recomendaciones', ['id'], unique=False)
    op.create_index(op.f('ix_recomendaciones_medico_id'), 'recomendaciones', ['medico_id'], unique=False)
    op.create_index(op.f('ix_recomendaciones_paciente_id'), 'recomendaciones', ['paciente_id'], unique=False)
    op.drop_table_comment(
        'recomendaciones',
        existing_comment='Recomendaciones generadas mediante Gemini API. Incluye PDF y estado de envio por correo.',
        schema=None
    )
    op.drop_constraint(op.f('roles_nombre_key'), 'roles', type_='unique')
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_nombre'), 'roles', ['nombre'], unique=True)
    op.alter_column('usuarios', 'rol_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usuarios', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('usuarios', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('usuarios_email_key'), 'usuarios', type_='unique')
    op.drop_constraint(op.f('usuarios_username_key'), 'usuarios', type_='unique')
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_rol_id'), 'usuarios', ['rol_id'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.drop_constraint(op.f('usuarios_rol_id_fkey'), 'usuarios', type_='foreignkey')
    op.create_foreign_key(None, 'usuarios', 'roles', ['rol_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.create_foreign_key(op.f('usuarios_rol_id_fkey'), 'usuarios', 'roles', ['rol_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_rol_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.create_unique_constraint(op.f('usuarios_username_key'), 'usuarios', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('usuarios_email_key'), 'usuarios', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('usuarios', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('usuarios', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('usuarios', 'rol_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_roles_nombre'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.create_unique_constraint(op.f('roles_nombre_key'), 'roles', ['nombre'], postgresql_nulls_not_distinct=False)
    op.create_table_comment(
        'recomendaciones',
        'Recomendaciones generadas mediante Gemini API. Incluye PDF y estado de envio por correo.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_recomendaciones_paciente_id'), table_name='recomendaciones')
    op.drop_index(op.f('ix_recomendaciones_medico_id'), table_name='recomendaciones')
    op.drop_index(op.f('ix_recomendaciones_id'), table_name='recomendaciones')
    op.create_index(op.f('idx_rec_paciente'), 'recomendaciones', ['paciente_id'], unique=False)
    op.create_index(op.f('idx_rec_medico'), 'recomendaciones', ['medico_id'], unique=False)
    op.alter_column('recomendaciones', 'fecha_generacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('recomendaciones', 'email_enviado',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_table_comment(
        'predicciones',
        'Resultados generados por modelos LR/RF luego del preprocesamiento de radiografias 64x64 en escala de grises.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'predicciones', type_='foreignkey')
    op.drop_constraint(None, 'predicciones', type_='foreignkey')
    op.create_foreign_key(op.f('predicciones_paciente_id_fkey'), 'predicciones', 'pacientes', ['paciente_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_predicciones_paciente_id'), table_name='predicciones')
    op.drop_index(op.f('ix_predicciones_medico_id'), table_name='predicciones')
    op.drop_index(op.f('ix_predicciones_id'), table_name='predicciones')
    op.drop_index(op.f('ix_predicciones_datos_clinicos_id'), table_name='predicciones')
    op.drop_index(op.f('ix_predicciones_cita_id'), table_name='predicciones')
    op.create_index(op.f('idx_pred_paciente'), 'predicciones', ['paciente_id'], unique=False)
    op.create_index(op.f('idx_pred_medico'), 'predicciones', ['medico_id'], unique=False)
    op.create_index(op.f('idx_pred_fecha'), 'predicciones', ['fecha_prediccion'], unique=False)
    op.alter_column('predicciones', 'fecha_prediccion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('predicciones', 'cita_id')
    op.drop_index(op.f('ix_permisos_id'), table_name='permisos')
    op.drop_index(op.f('ix_permisos_codigo'), table_name='permisos')
    op.create_unique_constraint(op.f('permisos_codigo_key'), 'permisos', ['codigo'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_pacientes_id'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_dni'), table_name='pacientes')
    op.create_unique_constraint(op.f('pacientes_dni_key'), 'pacientes', ['dni'], postgresql_nulls_not_distinct=False)
    op.alter_column('pacientes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'medicos', type_='foreignkey')
    op.create_foreign_key(op.f('medicos_usuario_id_fkey'), 'medicos', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_medicos_id'), table_name='medicos')
    op.alter_column('medicos', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_email_logs_recomendacion_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_id'), table_name='email_logs')
    op.alter_column('email_logs', 'fecha_evento',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'disponibilidad_medica', type_='foreignkey')
    op.create_foreign_key(op.f('disponibilidad_medica_medico_id_fkey'), 'disponibilidad_medica', 'medicos', ['medico_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_disponibilidad_medica_medico_id'), table_name='disponibilidad_medica')
    op.drop_index(op.f('ix_disponibilidad_medica_id'), table_name='disponibilidad_medica')
    op.alter_column('disponibilidad_medica', 'disponible',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'datos_clinicos', type_='foreignkey')
    op.create_foreign_key(op.f('datos_clinicos_paciente_id_fkey'), 'datos_clinicos', 'pacientes', ['paciente_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_datos_clinicos_paciente_id'), table_name='datos_clinicos')
    op.drop_index(op.f('ix_datos_clinicos_medico_id'), table_name='datos_clinicos')
    op.drop_index(op.f('ix_datos_clinicos_id'), table_name='datos_clinicos')
    op.create_index(op.f('idx_dc_paciente'), 'datos_clinicos', ['paciente_id'], unique=False)
    op.alter_column('datos_clinicos', 'fecha_registro',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'citas', type_='foreignkey')
    op.create_foreign_key(op.f('citas_paciente_id_fkey'), 'citas', 'pacientes', ['paciente_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_citas_paciente_id'), table_name='citas')
    op.drop_index(op.f('ix_citas_medico_id'), table_name='citas')
    op.drop_index(op.f('ix_citas_id'), table_name='citas')
    op.drop_index(op.f('ix_citas_fecha_cita'), table_name='citas')
    op.create_index(op.f('idx_citas_paciente'), 'citas', ['paciente_id'], unique=False)
    op.create_index(op.f('idx_citas_medico'), 'citas', ['medico_id'], unique=False)
    op.create_index(op.f('idx_citas_fecha'), 'citas', ['fecha_cita'], unique=False)
    op.alter_column('citas', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('citas', 'estado',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'pendiente'::character varying"))
    # ### end Alembic commands ###
